In [1]:
import pandas as pd

In [2]:
clientes = pd.read_csv("clientes.csv")
contas = pd.read_csv("contas1.0.csv")
transacoes = pd.read_csv("transcoes1.0.csv")

In [4]:
contas

,Unnamed: 0,num_conta,cod_cliente,cod_agencia,cod_colaborador,tipo_conta,data_abertura,saldo_total,saldo_disponivel,data_ultimo_lancamento,tipo_agencia
0,0,53,53,1,7,PF,2011-05-24 15:30:00 UTC,2984.7615,2814.67,2019-07-02 11:03:46 UTC,Agencia Fisica
1,1,190,190,1,7,PF,2014-10-17 14:48:00 UTC,4262.4322,4191.86,2021-03-25 12:00:15 UTC,Agencia Fisica
2,2,191,191,1,7,PF,2013-03-23 14:14:00 UTC,3266.5680,3080.71,2016-09-09 23:34:15 UTC,Agencia Fisica
3,3,203,203,1,7,PF,2016-08-03 16:13:00 UTC,21241.5424,19461.56,2022-12-28 07:58:24 UTC,Agencia Fisica
4,4,254,254,1,7,PF,2012-10-24 13:48:00 UTC,13335.6966,13197.54,2013-12-20 22:20:00 UTC,Agencia Fisica
...,...,...,...,...,...,...,...,...,...,...,...
994,994,466,466,10,8,PF,2022-10-26 14:13:00 UTC,7847.4165,9351.63,2022-12-30 00:00:00.319185 UTC,Agencia Fisica
995,995,764,764,10,8,PF,2022-09-08 11:06:00 UTC,65495.1872,64823.14,2022-12-29 23:59:59.964121 UTC,Agencia Fisica
996,996,488,488,10,18,PF,2022-07-16 10:16:00 UTC,8663.6081,6836.57,2022-12-30 00:00:00.966349 UTC,Agencia Fisica
997,997,395,395,10,95,PF,2022-12-01 15:27:00 UTC,23156.2065,21578.33,2022-12-30 00:00:00.607818 UTC,Agencia Fisica
998,998,355,355,10,100,PF,2022-10-22 14:50:00 UTC,10680.1524,10336.34,2022-12-29 23:59:59.739032 UTC,Agencia Fisica

In [5]:
transacoes

,Unnamed: 0,cod_transacao,num_conta,data_transacao,nome_transacao,valor_transacao,tipo_agencia
0,0,3100,256,2020-05-22 03:15:21 UTC,Saque,-130.00,Agencia Digital
1,1,28405,256,2021-06-29 11:52:38 UTC,Saque,-255.00,Agencia Digital
2,2,3190,256,2020-06-06 02:06:41 UTC,Compra DÃ©bito,-31.12,Agencia Digital
3,3,4466,256,2020-06-06 04:16:53 UTC,Compra DÃ©bito,-33.74,Agencia Digital
4,4,8455,256,2020-06-06 11:27:06 UTC,Compra DÃ©bito,-7.52,Agencia Digital
...,...,...,...,...,...,...,...
71994,71994,13438,252,2019-10-11 03:44:23 UTC,DepÃ³sito em espÃ©cie,41.47,Agencia Fisica
71995,71995,21265,252,2020-05-04 18:36:40 UTC,DepÃ³sito em espÃ©cie,15.40,Agencia Fisica
71996,71996,24126,252,2020-05-16 16:01:42 UTC,DepÃ³sito em espÃ©cie,44.24,Agencia Fisica
71997,71997,31758,252,2020-09-03 12:43:10 UTC,DepÃ³sito em espÃ©cie,54.85,Agencia Fisica
71998,71998,36759,252,2021-01-05 06:36:01 UTC,DepÃ³sito em espÃ©cie,6.20,Agencia Fisica

In [3]:
clientes

,cod_cliente,primeiro_nome,ultimo_nome,email,tipo_cliente,data_inclusao,cpfcnpj,data_nascimento,endereco,cep
0,28,Sabrina,Dias,moreiraemanuelly@example.org,PF,2017-04-03 16:11:00 UTC,357.081.496-39,2006-08-11,Praia de Duarte Vila Piratininga 81327-166 Fer...,95140-704
1,674,Luiz Felipe,Dias,pedroferreira@example.org,PF,2021-02-10 13:27:00 UTC,085.196.374-93,1995-10-11,"Avenida da Rosa, 654 JoÃ£o Paulo Ii 20295449 Nu...",76516-765
2,693,Renan,Dias,ogomes@example.net,PF,2020-01-21 13:12:00 UTC,783.416.059-10,1948-11-19,Jardim de Rodrigues Ipiranga 14161-477 Duarte ...,51779625
3,743,Clara,Dias,rafaelcorreia@example.org,PF,2019-05-06 11:39:00 UTC,589.237.610-95,1978-01-27,"ColÃ´nia Thomas Silva, 9 Tupi B 15771-946 Ferna...",19615792
4,769,AndrÃ©,Dias,danilo33@example.org,PF,2017-01-07 14:53:00 UTC,459.608.721-02,1990-08-25,"Rua Correia, 889 Diamante 59123250 AragÃ£o / RS",01672838
...,...,...,...,...,...,...,...,...,...,...
993,730,BÃ¡rbara,da ConceiÃ§Ã£o,enzo-gabrielcardoso@example.com,PF,2019-05-02 11:22:00 UTC,019.385.267-59,1966-03-06,"ChÃ¡cara de Martins, 85 Mantiqueira 26805-573 A...",08264521
994,772,Daniel,da ConceiÃ§Ã£o,raquel97@example.com,PF,2017-06-08 11:13:00 UTC,240.581.396-33,1971-07-20,"PÃ¡tio de Souza, 8 Vila Puc 47056676 Duarte / MS",55045-265
995,837,Theo,da ConceiÃ§Ã£o,ninacastro@example.org,PF,2014-03-18 10:30:00 UTC,058.734.129-79,1944-06-03,"Loteamento Pires, 4 Jardim Felicidade 69804-76...",88159-361
996,845,Pedro Lucas,da ConceiÃ§Ã£o,silveirabruno@example.com,PF,2020-12-16 15:14:00 UTC,347.028.591-88,1943-12-12,"Travessa Eloah Moura, 97 Alta TensÃ£o 2Âª SeÃ§Ã£o ...",36211-005
997,853,Milena,da ConceiÃ§Ã£o,ribeirodanilo@example.net,PF,2020-11-21 11:32:00 UTC,870.534.912-50,1999-04-22,"Feira de Vieira, 1 Planalto 31794137 Rodrigues...",15386938

In [6]:
clientes["estado"] = clientes["endereco"].str.slice(start=-2)
clientes

,cod_cliente,primeiro_nome,ultimo_nome,email,tipo_cliente,data_inclusao,cpfcnpj,data_nascimento,endereco,cep,estado
0,28,Sabrina,Dias,moreiraemanuelly@example.org,PF,2017-04-03 16:11:00 UTC,357.081.496-39,2006-08-11,Praia de Duarte Vila Piratininga 81327-166 Fer...,95140-704,SP
1,674,Luiz Felipe,Dias,pedroferreira@example.org,PF,2021-02-10 13:27:00 UTC,085.196.374-93,1995-10-11,"Avenida da Rosa, 654 JoÃ£o Paulo Ii 20295449 Nu...",76516-765,AP
2,693,Renan,Dias,ogomes@example.net,PF,2020-01-21 13:12:00 UTC,783.416.059-10,1948-11-19,Jardim de Rodrigues Ipiranga 14161-477 Duarte ...,51779625,RN
3,743,Clara,Dias,rafaelcorreia@example.org,PF,2019-05-06 11:39:00 UTC,589.237.610-95,1978-01-27,"ColÃ´nia Thomas Silva, 9 Tupi B 15771-946 Ferna...",19615792,SP
4,769,AndrÃ©,Dias,danilo33@example.org,PF,2017-01-07 14:53:00 UTC,459.608.721-02,1990-08-25,"Rua Correia, 889 Diamante 59123250 AragÃ£o / RS",01672838,RS
...,...,...,...,...,...,...,...,...,...,...,...
993,730,BÃ¡rbara,da ConceiÃ§Ã£o,enzo-gabrielcardoso@example.com,PF,2019-05-02 11:22:00 UTC,019.385.267-59,1966-03-06,"ChÃ¡cara de Martins, 85 Mantiqueira 26805-573 A...",08264521,SC
994,772,Daniel,da ConceiÃ§Ã£o,raquel97@example.com,PF,2017-06-08 11:13:00 UTC,240.581.396-33,1971-07-20,"PÃ¡tio de Souza, 8 Vila Puc 47056676 Duarte / MS",55045-265,MS
995,837,Theo,da ConceiÃ§Ã£o,ninacastro@example.org,PF,2014-03-18 10:30:00 UTC,058.734.129-79,1944-06-03,"Loteamento Pires, 4 Jardim Felicidade 69804-76...",88159-361,RR
996,845,Pedro Lucas,da ConceiÃ§Ã£o,silveirabruno@example.com,PF,2020-12-16 15:14:00 UTC,347.028.591-88,1943-12-12,"Travessa Eloah Moura, 97 Alta TensÃ£o 2Âª SeÃ§Ã£o ...",36211-005,PE
997,853,Milena,da ConceiÃ§Ã£o,ribeirodanilo@example.net,PF,2020-11-21 11:32:00 UTC,870.534.912-50,1999-04-22,"Feira de Vieira, 1 Planalto 31794137 Rodrigues...",15386938,RO

In [7]:
contas = contas.merge(clientes[["cod_cliente", "estado"]])
contas

,Unnamed: 0,num_conta,cod_cliente,cod_agencia,cod_colaborador,tipo_conta,data_abertura,saldo_total,saldo_disponivel,data_ultimo_lancamento,tipo_agencia,estado
0,0,53,53,1,7,PF,2011-05-24 15:30:00 UTC,2984.7615,2814.67,2019-07-02 11:03:46 UTC,Agencia Fisica,AL
1,1,190,190,1,7,PF,2014-10-17 14:48:00 UTC,4262.4322,4191.86,2021-03-25 12:00:15 UTC,Agencia Fisica,AL
2,2,191,191,1,7,PF,2013-03-23 14:14:00 UTC,3266.5680,3080.71,2016-09-09 23:34:15 UTC,Agencia Fisica,MT
3,3,203,203,1,7,PF,2016-08-03 16:13:00 UTC,21241.5424,19461.56,2022-12-28 07:58:24 UTC,Agencia Fisica,PA
4,4,254,254,1,7,PF,2012-10-24 13:48:00 UTC,13335.6966,13197.54,2013-12-20 22:20:00 UTC,Agencia Fisica,MA
...,...,...,...,...,...,...,...,...,...,...,...,...
993,994,466,466,10,8,PF,2022-10-26 14:13:00 UTC,7847.4165,9351.63,2022-12-30 00:00:00.319185 UTC,Agencia Fisica,PI
994,995,764,764,10,8,PF,2022-09-08 11:06:00 UTC,65495.1872,64823.14,2022-12-29 23:59:59.964121 UTC,Agencia Fisica,CE
995,996,488,488,10,18,PF,2022-07-16 10:16:00 UTC,8663.6081,6836.57,2022-12-30 00:00:00.966349 UTC,Agencia Fisica,PE
996,997,395,395,10,95,PF,2022-12-01 15:27:00 UTC,23156.2065,21578.33,2022-12-30 00:00:00.607818 UTC,Agencia Fisica,TO
997,998,355,355,10,100,PF,2022-10-22 14:50:00 UTC,10680.1524,10336.34,2022-12-29 23:59:59.739032 UTC,Agencia Fisica,AM

In [8]:
transacoes = transacoes.merge(contas[["num_conta", "estado"]])
transacoes

,Unnamed: 0,cod_transacao,num_conta,data_transacao,nome_transacao,valor_transacao,tipo_agencia,estado
0,0,3100,256,2020-05-22 03:15:21 UTC,Saque,-130.00,Agencia Digital,SP
1,1,28405,256,2021-06-29 11:52:38 UTC,Saque,-255.00,Agencia Digital,SP
2,2,3190,256,2020-06-06 02:06:41 UTC,Compra DÃ©bito,-31.12,Agencia Digital,SP
3,3,4466,256,2020-06-06 04:16:53 UTC,Compra DÃ©bito,-33.74,Agencia Digital,SP
4,4,8455,256,2020-06-06 11:27:06 UTC,Compra DÃ©bito,-7.52,Agencia Digital,SP
...,...,...,...,...,...,...,...,...
71916,71994,13438,252,2019-10-11 03:44:23 UTC,DepÃ³sito em espÃ©cie,41.47,Agencia Fisica,AP
71917,71995,21265,252,2020-05-04 18:36:40 UTC,DepÃ³sito em espÃ©cie,15.40,Agencia Fisica,AP
71918,71996,24126,252,2020-05-16 16:01:42 UTC,DepÃ³sito em espÃ©cie,44.24,Agencia Fisica,AP
71919,71997,31758,252,2020-09-03 12:43:10 UTC,DepÃ³sito em espÃ©cie,54.85,Agencia Fisica,AP
71920,71998,36759,252,2021-01-05 06:36:01 UTC,DepÃ³sito em espÃ©cie,6.20,Agencia Fisica,AP

In [ ]:
transacoes.to_csv("transacoes2.0.csv")
clientes.to_csv("clientes1.0.csv")
contas.to_csv("contas2.0.csv")